spring:
  application:
    name: gestor-producto

  r2dbc:
    url: r2dbc:h2:mem:///gestorproducto;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# API externa de cambio de moneda
external:
  currency:
    url: https://api.fastforex.io
    base: PEN
    api-key: f181db87c0-41e70636cc-t3bgfk
