-- 100 productos de tienda
INSERT INTO products (name, price, stock) VALUES ('Piano Digital', 1200.00, 2);
INSERT INTO products (name, price, stock) VALUES ('Violin Clasico', 750.00, 5);
INSERT INTO products (name, price, stock) VALUES ('Guitarra Acustica', 500.00, 10);
INSERT INTO products (name, price, stock) VALUES ('Laptop Lenovo ThinkPad E14', 3200.50, 15);
INSERT INTO products (name, price, stock) VALUES ('Smartphone Samsung Galaxy S22', 2800.00, 20);
INSERT INTO products (name, price, stock) VALUES ('Smartphone iPhone 14 Pro', 4800.99, 12);
INSERT INTO products (name, price, stock) VALUES ('Tablet iPad 10th Gen', 2300.75, 18);
INSERT INTO products (name, price, stock) VALUES ('Auriculares Sony WH-1000XM5', 1250.90, 25);
INSERT INTO products (name, price, stock) VALUES ('Smartwatch Apple Watch SE', 1150.00, 30);
INSERT INTO products (name, price, stock) VALUES ('Teclado Mecanico HyperX Alloy', 350.45, 40);
INSERT INTO products (name, price, stock) VALUES ('Mouse Logitech MX Master 3S', 420.00, 50);
INSERT INTO products (name, price, stock) VALUES ('Monitor LG UltraWide 34 Pulgadas', 2100.99, 10);
INSERT INTO products (name, price, stock) VALUES ('Impresora HP LaserJet Pro', 870.50, 22);
INSERT INTO products (name, price, stock) VALUES ('Camara Canon EOS Rebel T7', 3100.00, 8);
INSERT INTO products (name, price, stock) VALUES ('Camara Sony Alpha a6400', 4150.00, 6);
INSERT INTO products (name, price, stock) VALUES ('Disco Duro Externo Seagate 2TB', 350.00, 60);
INSERT INTO products (name, price, stock) VALUES ('SSD Samsung EVO 1TB', 690.90, 35);
INSERT INTO products (name, price, stock) VALUES ('Memoria USB Kingston 64GB', 55.99, 100);
INSERT INTO products (name, price, stock) VALUES ('Silla Gamer Cougar Armor', 780.00, 14);
INSERT INTO products (name, price, stock) VALUES ('Escritorio Ajustable FlexiSpot', 1250.00, 12);
INSERT INTO products (name, price, stock) VALUES ('Microondas LG 25L', 450.75, 28);
INSERT INTO products (name, price, stock) VALUES ('Refrigeradora Samsung 300L', 2450.00, 9);
INSERT INTO products (name, price, stock) VALUES ('Lavadora LG 17Kg', 1890.00, 11);
INSERT INTO products (name, price, stock) VALUES ('Cafetera Oster Espresso', 650.50, 20);
INSERT INTO products (name, price, stock) VALUES ('Licuadora Philips ProBlend', 280.99, 32);
INSERT INTO products (name, price, stock) VALUES ('Smart TV LG 55 Pulgadas OLED', 3400.00, 7);
INSERT INTO products (name, price, stock) VALUES ('Smart TV Samsung 65 Pulgadas QLED', 4100.00, 5);
INSERT INTO products (name, price, stock) VALUES ('Barra de Sonido Bose 700', 2100.00, 13);
INSERT INTO products (name, price, stock) VALUES ('Parlante JBL Charge 5', 580.00, 27);
INSERT INTO products (name, price, stock) VALUES ('Parlante Google Nest Audio', 390.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Consola PlayStation 5', 3800.00, 9);
INSERT INTO products (name, price, stock) VALUES ('Consola Xbox Series X', 3500.00, 8);
INSERT INTO products (name, price, stock) VALUES ('Nintendo Switch OLED', 2100.00, 16);
INSERT INTO products (name, price, stock) VALUES ('Juego FIFA 25', 350.00, 50);
INSERT INTO products (name, price, stock) VALUES ('Juego Call of Duty MW3', 370.00, 45);
INSERT INTO products (name, price, stock) VALUES ('Juego Zelda Tears of the Kingdom', 380.00, 38);
INSERT INTO products (name, price, stock) VALUES ('Bicicleta Trek Marlin 7', 2990.00, 6);
INSERT INTO products (name, price, stock) VALUES ('Scooter Electrico Xiaomi Pro 2', 1950.00, 11);
INSERT INTO products (name, price, stock) VALUES ('Patines Rollerblade Macroblade', 650.00, 20);
INSERT INTO products (name, price, stock) VALUES ('Balon de Futbol Adidas Pro', 220.00, 33);
INSERT INTO products (name, price, stock) VALUES ('Zapatillas Nike Air Max 270', 780.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Zapatillas Adidas Ultraboost', 790.00, 28);
INSERT INTO products (name, price, stock) VALUES ('Zapatillas Puma RS-X', 620.00, 22);
INSERT INTO products (name, price, stock) VALUES ('Polera Puma Hoodie', 180.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Casaca Columbia Impermeable', 420.00, 15);
INSERT INTO products (name, price, stock) VALUES ('Mochila North Face Borealis', 350.00, 18);
INSERT INTO products (name, price, stock) VALUES ('Lentes Ray-Ban Aviator', 560.00, 12);
INSERT INTO products (name, price, stock) VALUES ('Perfume Dior Sauvage 100ml', 580.00, 14);
INSERT INTO products (name, price, stock) VALUES ('Perfume Carolina Herrera 212 Men', 420.00, 16);
INSERT INTO products (name, price, stock) VALUES ('Perfume Paco Rabanne Invictus', 390.00, 19);
INSERT INTO products (name, price, stock) VALUES ('Libro Clean Code', 150.00, 45);
INSERT INTO products (name, price, stock) VALUES ('Libro Effective Java', 210.00, 30);
INSERT INTO products (name, price, stock) VALUES ('Libro Domain-Driven Design', 270.00, 20);
INSERT INTO products (name, price, stock) VALUES ('Juego de Sartenes Tefal 5pz', 340.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Olla Arrocera Oster 2L', 180.00, 35);
INSERT INTO products (name, price, stock) VALUES ('Hervidor Electrico Philips', 130.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Ventilador Samurai 16 Pulgadas', 220.00, 28);
INSERT INTO products (name, price, stock) VALUES ('Aspiradora Dyson V11', 2150.00, 7);
INSERT INTO products (name, price, stock) VALUES ('Plancha Rowenta ProMaster', 190.00, 26);
INSERT INTO products (name, price, stock) VALUES ('Colchon Spring Air Queen', 2600.00, 5);
INSERT INTO products (name, price, stock) VALUES ('Sofa 3 Plazas MueblesCo', 3200.00, 4);
INSERT INTO products (name, price, stock) VALUES ('Comedor 6 Sillas Moderno', 2800.00, 6);
INSERT INTO products (name, price, stock) VALUES ('Ropero MDP 3 Puertas', 1500.00, 8);
INSERT INTO products (name, price, stock) VALUES ('Cuna de Madera Bebesit', 1100.00, 10);
INSERT INTO products (name, price, stock) VALUES ('Carro a Control Remoto Tamiya', 390.00, 20);
INSERT INTO products (name, price, stock) VALUES ('Drone DJI Mini 3 Pro', 3100.00, 7);
INSERT INTO products (name, price, stock) VALUES ('Patineta Skate Element', 320.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Raqueta Tenis Wilson Pro', 480.00, 18);
INSERT INTO products (name, price, stock) VALUES ('Guantes Box Everlast Pro', 290.00, 20);
INSERT INTO products (name, price, stock) VALUES ('Set Mancuernas Ajustables 20kg', 520.00, 12);
INSERT INTO products (name, price, stock) VALUES ('Colchoneta Yoga Adidas', 160.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Suplemento Whey Protein ON', 350.00, 22);
INSERT INTO products (name, price, stock) VALUES ('Creatina Universal 300g', 190.00, 30);
INSERT INTO products (name, price, stock) VALUES ('Bebida Energetica Monster Pack 12', 120.00, 50);
INSERT INTO products (name, price, stock) VALUES ('Cerveza Corona Pack 24', 180.00, 60);
INSERT INTO products (name, price, stock) VALUES ('Whisky Johnnie Walker Black 1L', 250.00, 18);
INSERT INTO products (name, price, stock) VALUES ('Ron Zacapa 23 Anos 750ml', 280.00, 14);
INSERT INTO products (name, price, stock) VALUES ('Vodka Absolut 1L', 120.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Vino Tinto Malbec Trapiche', 90.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Agua Mineral San Luis 20L', 35.00, 100);
INSERT INTO products (name, price, stock) VALUES ('Gaseosa Coca Cola 3L', 15.00, 120);
INSERT INTO products (name, price, stock) VALUES ('Aceite de Oliva Carbonell 1L', 65.00, 45);
INSERT INTO products (name, price, stock) VALUES ('Arroz Costeno 5kg', 28.00, 80);
INSERT INTO products (name, price, stock) VALUES ('Azucar Rubia 5kg', 26.00, 70);
INSERT INTO products (name, price, stock) VALUES ('Harina Blanca Flor 1kg', 12.00, 90);
INSERT INTO products (name, price, stock) VALUES ('Fideos Don Vittorio 1kg', 14.00, 85);
INSERT INTO products (name, price, stock) VALUES ('Leche Gloria Evaporada 400g', 5.50, 200);
INSERT INTO products (name, price, stock) VALUES ('Huevos de Gallina 30un', 24.00, 150);
INSERT INTO products (name, price, stock) VALUES ('Queso Andino 1kg', 38.00, 60);
INSERT INTO products (name, price, stock) VALUES ('Pollo Entero 2kg', 28.00, 70);
INSERT INTO products (name, price, stock) VALUES ('Carne de Res Bife Angosto 1kg', 55.00, 50);
INSERT INTO products (name, price, stock) VALUES ('Filete de Pescado Bonito 1kg', 32.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Camarones Frescos 1kg', 70.00, 35);
INSERT INTO products (name, price, stock) VALUES ('Manzanas Fuji 1kg', 12.00, 60);
INSERT INTO products (name, price, stock) VALUES ('Platanos de Seda 1kg', 8.00, 75);
INSERT INTO products (name, price, stock) VALUES ('Naranjas Jugosas 1kg', 10.00, 65);
INSERT INTO products (name, price, stock) VALUES ('Uvas Red Globe 1kg', 14.00, 55);
INSERT INTO products (name, price, stock) VALUES ('Papayas de la Selva 1kg', 9.00, 45);
INSERT INTO products (name, price, stock) VALUES ('Paltas Hass 1kg', 18.00, 40);
INSERT INTO products (name, price, stock) VALUES ('Sandia Entera', 20.00, 30);
INSERT INTO products (name, price, stock) VALUES ('Pina Golden', 15.00, 25);
INSERT INTO products (name, price, stock) VALUES ('Mango Kent 1kg', 16.00, 35);
